baseURL = "https://eraykalkan.com"
languageCode = "en-us"
title = "Eray's Humble Software Blog"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-123456789-1"

enableRobotsTXT = true
canonifyURLs = true

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Java"
    pre = "coffee"
    url = "/java/"
    weight = 2
  [[menu.main]]
    name = "Spring Framework"
    pre = "feather"
    url = "/spring/"
    weight = 3
  [[menu.main]]
    name = "Git"
    pre = "git-commit"
    url = "/git/"
    weight = 4  
  [[menu.main]]
    name = "Algorithms"
    pre = "edit"
    url = "/algorithms/"
    weight = 5   
  [[menu.main]]
    name = "Algorithms"
    pre = "edit"
    url = "/algorithms/"
    weight = 6   
  [[menu.main]]
    name = "C++"
    pre = "cuttlefish"
    url = "/cplusplus/"
    weight = 7
  [[menu.main]]
    name = "Unreal Engine"
    pre = "edit"
    url = "/unrealengine/"
    weight = 8   
  [[menu.main]]
    name = "About"
    pre = "smile"
    url = "/about/"
    weight = 9
  [[menu.main]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 10

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the my software blog. The site may seem a bit plain but it serves its purpose and it is bandwith friendly. You will find stuff mostly about Java and frameworks that use Java. This is a newly born blog so feel free to check it again in a few days if you can't find what you're looking for as I'm planning to cover from fundamental stuff to advanced level stuff"
